### ISSUE TITLE
Kijk naar partials

### ISSUE THREAD

**Issue by SamaraFellaDina** [Naddybs/the-met-redesign#2]
Hee! Ik zag de volgende code in je index staan:

<header class="hero-section">
    <section class="hero-image-bg">
        <img src="/assets/painting-1.webp" alt="" style="width:100%; max-width: 300px;"> 
        <img src="/assets/painting-2.webp" alt="" style="width:100%; max-width: 300px;">
        <img src="/assets/painting-3.webp" alt="" style="width:100%; max-width: 300px;">
        <img src="/assets/painting-4.webp" alt="" style="width:100%; max-width: 300px;">
    </section>

    <aside class="hero-overlay"></aside> 

    <article class="hero-content">
        <h1 class="hero-title">
            <span class="red-block">The Met Museum </span>
            <span class="black-block">Collection</span>
        </h1>
    </article>
</header>

Je hebt nu volgens mij twee headers. Eentje als partial en een  in je index, klopt dat. Is de website dan goed te overzien? Daarnaast zie ik nog geen footer partial. Je kan ook als je bepaalde componenten op meerdere pagina' gebruikt een partial ervan maken ;)

**Comment by Naddybs** [comment]
Bedankt voor je opmerking, dat klopt. Ik heb een partial aangemaakt voor de navigatie, omdat ik die op verschillende pagina's gebruik. De header tag in mijn index gebruik ik specifiek voor de hero section, omdat die per pagina verschilt. Ik heb er bewust voor gekozen om de hero niet in de partial te zetten, zodat elke pagina een andere uitsraling heeft. De footer moet ik idd nog toevoegen thankyou!!

**Comment by Naddybs** [comment]
Bedankt voor je opmerking, dat klopt. Ik heb een partial aangemaakt voor de navigatie, omdat ik die op verschillende pagina's gebruik. De header tag in mijn index gebruik ik specifiek voor de hero section, omdat die per pagina verschilt. Ik heb er bewust voor gekozen om de hero niet in de partial te zetten, zodat elke pagina een andere uitsraling heeft. De footer moet ik idd nog toevoegen thankyou!!
